import React from "react";
import PropTypes from "prop-types";

const WaveForm = ({ id, children }) => {
    return <div id={id}>{children}</div>;
};

WaveForm.defaultProps = {
    id: "waveform",
    audioRate: 1,
    autoCenter: true,
    backend: "WebAudio",
    barHeight: 1,
    barRadius: 0,
    closeAudioContext: false,
    cursorColor: "#333",
    cursorWidth: 1,
    fillParent: true,
    forceDecode: false,
    height: 128,
    hideScrollbar: false,
    interact: true,
    loopSelection: true,
    maxCanvasWidth: 4000,
    mediaControls: false,
    mediaType: "audio",
    minPxPerSec: 50,
    normalize: false,
    partialRender: false,
    pixelRatio: window.devicePixelRatio,
    plugins: [],
    progressColor: "purple",
    removeMediaElementOnDestroy: true,
    responsive: false,
    scrollParent: false,
    skipLength: 2,
    splitChannels: false,
    waveColor: "violet",
    xhr: {},
};

WaveForm.PropTypes = {
    id: PropTypes.string.isRequired,
    audioRate: PropTypes.number,
    audioContext: PropTypes.object,
    audioScriptProcessor: PropTypes.object,
    autoCenter: PropTypes.boolean,
    backend: PropTypes.string,
    backgroundColor: PropTypes.string,
    barGap: PropTypes.number,
    barHeight: PropTypes.number,
    barRadius: PropTypes.number,
    barWidth: PropTypes.number,
    closeAudioContext: PropTypes.boolean,
    cursorColor: PropTypes.string,
    cursorWidth: PropTypes.number,
    fillParent: PropTypes.boolean,
    forceDecode: PropTypes.boolean,
    height: PropTypes.number,
    hideScrollbar: PropTypes.boolean,
    interact: PropTypes.boolean,
    loopSelection: PropTypes.boolean,
    maxCanvasWidth: PropTypes.number,
    mediaControls: PropTypes.boolean,
    mediaType: PropTypes.oneOf(["audio", "video"]),
    minPxPerSec: PropTypes.number,
    normalize: PropTypes.boolean,
    partialRender: PropTypes.boolean,
    pixelRatio: PropTypes.number,
    plugins: PropTypes.array,
    progressColor: PropTypes.string,
    removeMediaElementOnDestroy: PropTypes.boolean,
    renderer: PropTypes.Object,
    responsive: PropTypes.node,
    scrollParent: PropTypes.boolean,
    skipLength: PropTypes.number,
    splitChannels: PropTypes.boolean,
    waveColor: PropTypes.string,
    xhr: PropTypes.Object,
}

export default WaveForm;
